tickers:
  - NVDA
  - MSFT
  - AAPL
  - AMZN
  - META
  - AVGO
  - GOOGL
  - TSLA
  - GOOG
  - BRK-B
  - JPM
  - V
  - LLY
  - NFLX
  - XOM
  - MA
  - JNJ
  - COST
  - WMT
  - HD
  - ORCL
  - PG
  - ABBV
  - PLTR
  - BAC
  - CVX
  - GE
  - UNH
  - CSCO
  - AMD
  - WFC
  - KO
  - PM
  - CRM
  - GS
  - ABT
  - IBM
  - LIN
  - MCD
  - RTX
  - DIS
  - MRK
  - T
  - CAT
  - PEP
  - UBER
  - TXN
  - VZ
  - INTU
  - MS
  - TMO
  - NOW
  - BKNG
  - C
  - AXP
  - BA
  - QCOM
  - SPGI
  - GEV
  - ISRG
  - SCHW
  - BLK
  - ACN
  - BSX
  - AMGN
  - TJX
  - NEE
  - ADBE
  - LOW
  - COF
  - PGR
  - PFE
  - HON
  - GILD
  - ETN
  - ANET
  - SYK
  - AMAT
  - APH
  - LRCX
  - UNP
  - MU
  - DHR
  - ADI
  - CMCSA
  - BX
  - DE
  - PANW
  - COP
  - ADP
  - TMUS
  - MDT
  - KLAC
  - MO
  - SNPS
  - INTC
  - CRWD
  - PLD
  - WELL
  - SO
  - CB
  - ICE
  - MMC
  - VRTX
  - SBUX
  - CEG
  - PH
  - CME
  - BMY
  - DUK
  - AMT
  - KKR
  - LMT
  - CDNS
  - TT
  - NKE
  - CVS
  - RCL
  - ORLY
  - MCK
  - SHW
  - MMM
  - DASH
  - WM
  - GD
  - PNC
  - NEM
  - CI
  - MDLZ
  - AON
  - NOC
  - MCO
  - TDG
  - MSI
  - EQIX
  - FI
  - AJG
  - USB
  - BK
  - EMR
  - CTAS
  - JCI
  - ITW
  - HWM
  - ECL
  - AZO
  - WMB
  - HCA
  - ELV
  - ZTS
  - CL
  - PYPL
  - EOG
  - VST
  - HLT
  - APD
  - COIN
  - UPS
  - FCX
  - TRV
  - URI
  - TEL
  - NSC
  - MAR
  - APO
  - TFC
  - ADSK
  - CSX
  - REGN
  - AEP
  - NXPI
  - FAST
  - CMG
  - AXON
  - ROP
  - PWR
  - GM
  - ABNB
  - BDX
  - CMI
  - SPG
  - MPC
  - PSX
  - SLB
  - ALL
  - CARR
  - DLR
  - SRE
  - PCAR
  - O
  - AFL
  - KMI
  - GLW
  - LHX
  - IDXX
  - D
  - FDX
  - CTVA
  - COR
  - WDAY
  - FTNT
  - ROST
  - AMP
  - CBRE
  - RSG
  - EW
  - AIG
  - VLO
  - OKE
  - F
  - DHI
  - PSA
  - MET
  - EXC
  - TGT
  - GWW
  - PAYX
  - BKR
  - MSCI
  - XYZ
  - CCI
  - MNST
  - KMB
  - EBAY
  - AME
  - CPRT
  - DDOG
  - XEL
  - KR
  - MPWR
  - RMD
  - PEG
  - YUM
  - KDP
  - DAL
  - ETR
  - KVUE
  - DELL
  - EA
  - ROK
  - TTWO
  - NDAQ
  - SYY
  - PRU
  - VMC
  - HIG
  - CSGP
  - VRSK
  - MLM
  - FIS
  - GRMN
  - ED
  - HUM
  - MCHP
  - TRGP
  - VICI
  - CTSH
  - CAH
  - STX
  - XYL
  - NUE
  - OTIS
  - FICO
  - WEC
  - ACGL
  - UAL
  - GEHC
  - CCL
  - A
  - WAB
  - OXY
  - PCG
  - TSCO
  - USD
  - STT
  - WTW
  - DD
  - IR
  - MTB
  - IQV
  - LEN
  - EQT
  - VTR
  - EFX
  - RJF
  - FITB
  - BR
  - ADM
  - EXR
  - DXCM
  - HPE
  - NRG
  - SYF
  - DTE
  - ODFL
  - KEYS
  - AWK
  - WDC
  - AVB
  - FANG
  - WBD
  - AEE
  - IRM
  - PPL
  - GIS
  - IBKR
  - BRO
  - HSY
  - MTD
  - VLTO
  - ATO
  - PHM
  - LYV
  - PTC
  - HBAN
  - EXPE
  - CHTR
  - NTRS
  - HPQ
  - IP
  - PPG
  - TDY
  - DOV
  - CBOE
  - RF
  - CNP
  - STZ
  - DG
  - STE
  - TYL
  - DRI
  - ULTA
  - KHC
  - CINF
  - HUBB
  - ES
  - NVR
  - TROW
  - LDOS
  - TTD
  - WSM
  - PODD
  - LH
  - SMCI
  - CPAY
  - CHD
  - VRSN
  - DVN
  - NTAP
  - LULU
  - SW
  - CFG
  - FE
  - SBAC
  - JBL
  - DLTR
  - EQR
  - CDW
  - EL
  - CMS
  - WRB
  - K
  - GPN
  - ON
  - EIX
  - ZBH
  - GDDY
  - TPR
  - EXE
  - FSLR
  - DGX
  - NI
  - BIIB
  - TRMB
  - AMCR
  - GPC
  - LVS
  - HAL
  - KEY
  - IT
  - WY
  - LUV
  - PKG
  - TER
  - CTRA
  - STLD
  - FFIV
  - LII
  - PNR
  - MKC
  - J
  - INVH
  - DECK
  - WST
  - WAT
  - DOW
  - APTV
  - SNA
  - ESS
  - TPL
  - IFF
  - LNT
  - MAA
  - L
  - GEN
  - EXPD
  - PFG
  - EVRG
  - FTV
  - TSN
  - ZBRA
  - ROL
  - MAS
  - BLDR
  - DPZ
  - OMC
  - KIM
  - CHRW
  - HOLX
  - COO
  - ALLE
  - TXT
  - CLX
  - EG
  - BBY
  - BALL
  - LYB
  - FDS
  - CNC
  - CF
  - INCY
  - AVY
  - FOXA
  - BAX
  - ARE
  - IEX
  - DOC
  - TKO
  - VTRS
  - NDSN
  - HST
  - POOL
  - REG
  - JKHY
  - CPT
  - RL
  - UDR
  - SWK
  - GL
  - SWKS
  - AKAM
  - JBHT
  - BG
  - SJM
  - NWSA
  - NCLH
  - DAY
  - GNRC
  - PAYC
  - AIZ
  - WYNN
  - HII
  - PNW
  - HAS
  - SOLV
  - MOS
  - RVTY
  - UHS
  - BXP
  - ALB
  - IPG
  - IVZ
  - EPAM
  - ALGN
  - MOH
  - AES
  - KMX
  - MTCH
  - CAG
  - TECH
  - PSKY
  - TAP
  - ERIE
  - MRNA
  - HRL
  - AOS
  - HSIC
  - LKQ
  - MGM
